# Page settings
# baseurl = "https://acpbrasil.github.io/acpbrasil-blog-hugo/"
baseurl = "http://www.acpbrasil.com/"
title = "ACP Brasil"
languageCode = "pt-br"
theme = "elate"

# Define the number of posts per page
paginate = 5

[params]

  # Format dates with Go's time formatting
  date_format = "2 January, 2006"
  
  custom_css = ["css/custom.css"] # Custom CSS files for Home page
  custom_pages_css = ["css/custom-pages.css"] # Custom CSS files for all other pages

  # Meta
  # TODO Me adicionar como autor
  # author = "Denis C de Azevedo <denis.azevedo@gmail.com>"
  author = "ACP Brasil"
  description = "Empresa de recrutamento e consultoria de enfermeiros para os EUA"
  email = "contato@acpediatrics.com"

  # TODO Definir keywords com as gurias
  defaultKeywords = [ "acp", "eua", "blog", "enfermeiros", "nurse", "recrutamento", "migração", "emprego", "job" ]

  
  # Forms configuration
  emailsSubjectPrefix = "[ACP]"
  
  # Navigation
  [params.navigation]
    brand = "ACP Brasil"
    home = "Home"
    work = "Por que a ACP?"
    services = "Serviços"
    # TODO Habilitar Testemunhos?
    # testimonials = "Testemunhos"
    about = "Sobre"
    contact = "Contato"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "formulario/"
      name = "Faça parte"
      weight = 10
    [[menu.postpend]]
      url = "blog/"
      name = "Blog"
      weight = 11
  
  # Hero section
  [params.hero]
    title = "ACP: Recrutando, orientando e empregando"
    subtitle = "A enfermagem como passaporte para os EUA."
    description = "Trabalhar como enfermeiro na Advanced Care Pediatrics é a sua oportunidade de expandir seus conhecimentos e alavancar a sua carreira como enfermeiro nos Estados Unidos."
    # video settings
    videoUrl = "https://www.advancedcarepediatrics.com/wp-content/uploads/2017/03/homepage-header.mp4"
    videoImage = "bg/homepage-header-still.jpg"
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Quem somos nós?"
    description = "Conheça um pouco mais sobre a ACP."
    # TODO Testar o link no github.io
    url = "sobre/"
    button = "Saiba mais"
    icon = "icon-people"

  [[params.intro.item]]
    title = "Está interessado?"
    description = "Nos conte um pouco sobre você."
    url = "formulario/"
    button = "Saiba mais"
    icon = "icon-note"

  [[params.intro.item]]
    # title = "Salários e benefícios nos EUA"
    title = "Salários e benefícios"
    description = "Conheça as nossas vantagens nos EUA."
    url = "salarios-e-beneficios/"
    button = "Saiba mais"
    icon = "icon-wallet"

  [params.intro.video]
    # TODO Habilitar o vídeo assim que estiver pronto
    enable = false
    title = "Assista ao vídeo"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=FSGWhw_RA8Y"


  # Work section
  [params.work]
    enable = true
    title = "Por que a ACP?"
    description = "ACP atua ativamente na busca de enfermeiros qualificados para integrar a equipe da ACP na área de enfermagem domiciliar. O nosso time de profissionais irá junto com você percorrer e transpor todas as etapas necessárias para <strong>você exercer a enfermagem nos Estados Unidos como profissional habilitado</strong>."
    footertext = "Nós ajudaremos você em todas estas etapas."
    dataContent = "porqueacp" # Arquivo dentro de data/ com o conteúdo dessa seção


  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testemunhos"
    description = "Conheça a história de enfermeiros que já passaram por esse processo e também de nossos colaboradores."

    [[params.testimonials.item]]
      quote = "&ldquo;Desde o primeiro dia que conversei com a ACP, senti imediatamente a sinceridade e acolhimento da ACP em seus objetivos de fornecer o melhor cuidado possível aos nossos pacientes e familiares, mantendo sempre uma relação profissional e de cuidado com toda a equipe.&rdquo;"
      person = 'T. O’Brein <span class="subtext">Técnica em Enfermagem</span>'
      img = "person1.jpg"
      alt = "T. O’Brein"

    [[params.testimonials.item]]
      quote = "&ldquo;Eu tenho trabalhado em assistência domiciliar durante 19 anos e para diferentes empresas. A ACP é a única empresa que reconhece o enfermeiro, mensalmente e anualmente, pelo esforço e dedicação. Eu amo trabalhar para a ACP, eles cuidam de mim. Sempre que tenho uma preocupação sou ouvida. Oferece salários e benefícios competitivos. ACP você é a melhor e sou muito grata por tudo o que faz!&rdquo;"
      person = 'D. Hurt <span class="subtext">Enfermeira</span>'
      img = "person2.jpg"
      alt = "D. Hurt"
    
    [[params.testimonials.item]]
      quote = "&ldquo;Em 2007 consegui minha licença pela <em>Board of Nursing Colorado</em>. Contei com uma americana da área da saúde para entender todas as etapas: isso foi fundamental! Passei na 1ª tentativa na prova do Nclex! Não consegui _sponsor_ devido à recessão nos EUA na época. Quando conheci a Greice, fiquei extremamente interessada em participar da ACP Brasil e ajudar colegas com minha experiência a concretizar este sonho!&rdquo;"
      person = 'F. Morales <span class="subtext">Consultora</span>'
      img = "person3.jpg"
      alt = "F. Morales"



  # Services section
  [params.services]
    enable = true
    title = "Serviços"
    description = "Conheça os nossos serviços e formas de atuação."

    [[params.services.item]]
      title = "Enfermeiros"
      description = "Cuidaremos do seu processo de forma personalizada, traçando uma meta realista de acordo com as suas necessidades e experiência profissional."
      icon = "icon-people"

    [[params.services.item]]
      title = "Universidades &amp; Instituições de Ensino"
      # TODO Arrumar a cor do link
      description = 'Oferecemos workshops gratuitos para apresentar essa oportunidade aos alunos e professores. <a class="inner-section-link" href="#" data-nav-section="contact">Entre em contato</a> para saber como.'
      icon = "icon-graduation"

  # About section
  [params.about]
    enable = true
    title = "Sobre"
    description = "Empresa de recrutamento e consultoria de enfermeiros para os EUA.<br><br><a class='btn btn-primary' href='sobre/'>Conheça mais</a>"

    # [[params.about.item]]
    #   name = "Greice"
    #   position = "Fundadora"
    #   description = "<code class='TODO'>Descrição</code>"
    #   img = "person1.jpg"
    #   alt = "Greice"
    #   # social = [
    #   #   ["icon-twitter", "#"],
    #   #   ["icon-facebook", "#"],
    #   #   ["icon-linkedin", "#"]
    #   # ]      

    # [[params.about.item]]
    #   name = "Flaviane"
    #   position = "Consultora"
    #   description = "<code class='TODO'>Descrição</code>"
    #   img = "person2.jpg"
    #   alt = "Flaviane"
    #   # social = [
    #   #   ["icon-facebook", "#"],
    #   #   ["icon-linkedin", "#"]
    #   # ]

    # [[params.about.item]]
    #   name = "Izabelle"
    #   position = "Consultora"
    #   description = "<code class='TODO'>Descrição</code>"
    #   img = "person3.jpg"
    #   alt = "Person3"
    #   # social = [
    #   #   ["icon-twitter", "#"],
    #   #   ["icon-facebook", "#"],
    #   #   ["icon-linkedin", "#"]
    #   # ]
    

  # Counters section
  [params.counters]
    enable = true
    title = "ACP em números"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Funcionários"
      icon = "icon-emotsmile"
      from = 0
      to = 450
      interval = 200
      speed = 4000

    [[params.counters.item]]
      description = "Crescimento anual (em %)"
      icon = "icon-graph"
      from = 0
      to = 40
      interval = 50
      speed = 3000

    [[params.counters.item]]
      # TODO Adicionar um link pra essa list INC 5000?
      description = "Lista INC 5000 por dois anos consecutivos"
      icon = "icon-trophy"
      from = 5000
      to = 5000
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Vagas de emprego disponíveis"
      # TODO pin? feed? info? magnifier?
      icon = "icon-pin"
      from = 0
      to = 237
      interval = 100
      speed = 4000


  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    emailTo = "contato@acpediatrics.com"
    emailCc = [
      "fmorales@acpediatrics.com",
      "igindri@acpediatrics.com",
      "denisazevedo@gmail.com"
    ]
    title = "Contato"
    description = "Quer fazer parte do nosso time?<br>Quer iniciar o processo?<br>Tem dúvidas?<br>Entre em contato com a nossa equipe no Brasil."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Florianópolis / SC"],
        ["icon-phone", "+55 (48) 99176-0676<br>+55 (48) 99176-3535"],
        ["icon-envelope", "<a href='mailto:contato@acpediatrics.com?subject=Contato'>contato@acpediatrics.com</a>"],
        # TODO Colocar a url da ACP Brasil também?
        ["icon-globe", '<a href="https://www.advancedcarepediatrics.com/" target="_blank">ACP Home care</a><br><a href="http://www.acpbrasil.com/" target="_blank">ACP Brasil</a>']
      ]

    subject = "Nova mensagem do site!"
    # Form input fields
    name = "Nome"
    email = "Email"
    phone = "Telefone"
    message = "Mensagem"
    button = "Enviar mensagem"

  # Footer section
  [params.footer]
    enable = true
    copyright = "&copy; ACP Brasil. Todos os direitos reservados."
    links = [
        ["icon-instagram", "https://www.instagram.com/acpbrasil/"],
        # TODO Mudar o link do Facebook pra acpbrasil
        ["icon-facebook", "https://www.facebook.com/enfermeiroseua"],
        ["icon-youtube", "https://www.youtube.com/channel/UCTMLh7W0ZyYm_NopZKVVNDg"],
        # ["icon-twitter", "#twitter"]
      ]
