# Page settings
baseurl = "https://acpbrasil.github.io/acpbrasil-blog-hugo/"
title = "ACP Recrutamento"
languageCode = "pt-br"
theme = "elate"

[params]

  # Format dates with Go's time formatting
  date_format = "2 January, 2006"
  
  custom_css = ["css/custom.css"] # Custom CSS files for Home page
  custom_pages_css = ["css/custom-pages.css"] # Custom CSS files for all other pages

  # Meta
  author = ""
  description = ""
  email = "denisazevedo@gmail.com"
  
  # Forms configuration
  emailsSubjectPrefix = "[ACP]"
  # TODO Add other emails here (_cc)
  
  # Navigation
  [params.navigation]
    brand = "ACP Recrutamento"
    home = "Home"
    work = "Por que a ACP?"
    services = "Serviços"
    testimonials = "Testemunhos"
    about = "Sobre"
    contact = "Contato"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "/blog/"
      name = "<code>[Blog]</code>"
      weight = 10
    [[menu.postpend]]
      url = "/form/"
      name = "<code>[Form]</code>"
      weight = 10
  
  # Hero section
  [params.hero]
    title = "ACP: Recrutando, orientando e empregando"
    subtitle = "A enfermagem como passaporte para os EUA."
    description = "Trabalhar como enfermeiro na Advanced Care Pediatrics é a sua oportunidade de expandir seus conhecimentos e alavancar a sua carreira como enfermeiro nos Estados Unidos."
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Quem somos nós?"
    description = "Conheça um pouco mais sobre a ACP."
    # TODO Testar o link no github.io
    url = "/sobre/"
    button = "Saiba mais"
    icon = "icon-people"

  [[params.intro.item]]
    title = "Está interessado?"
    description = "Nos conte um pouco sobre você."
    url = "form/"
    button = "Saiba mais"
    icon = "icon-note"

  [[params.intro.item]]
    # title = "Salários e benefícios nos EUA"
    title = "Salários e benefícios"
    description = "Conheça as nossas vantagens nos EUA."
    url = "/salarios-e-beneficios/"
    button = "Saiba mais"
    icon = "icon-wallet"

  [params.intro.video]
    enable = true
    title = "Assista ao vídeo"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=FSGWhw_RA8Y"


  # Work section
  [params.work]
    enable = true
    title = "Por que a ACP?"
    description = "ACP atua ativamente na busca enfermeiros qualificados para integrar a equipe da ACP na área de enfermagem domiciliar e hospitalar. O nosso time de profissionais irá junto com você percorrer e transpor todas as etapas necessárias para <strong>você exercer a enfermagem nos Estados Unidos como profissional habilitado</strong>."
    footertext = "Nós ajudaremos você em todas essas etapas."
    dataContent = "porqueacp" # Arquivo dentro de data/ com o conteúdo dessa seção


  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testemunhos"
    description = "Conheça a história de enfermeiros que já passaram por esse processo e também de nossos colaboradores."

    [[params.testimonials.item]]
      quote = "&ldquo;Em 2007 consegui minha licença pela <em>Board of Nursing Colorado</em>. Contei com uma americana da área da saúde para entender todas as etapas: isso foi fundamental! Passei na 1ª tentativa na prova do Nclex! Não consegui sponsor devido a recessão nos EUA na época. Quando conheci a Greice, fiquei extremamente interessada em participar da ACP Recrutamento e ajudar colegas com minha experiência a concretizar este sonho!&rdquo;"
      person = 'Flaviane Morales <span class="subtext">Fundadora <a href="http://www.acpbrasil.com/" target="_blank">ACP Recrutamento</a></span>'
      img = "person1.jpg"
      alt = "Flaviane Morales"

    [[params.testimonials.item]]
      quote = "&ldquo;<code class='TODO'>Citação</code>&rdquo;"
      person = 'Nurse Greice #1 <span class="subtext">Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a></span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;<code class='TODO'>Citação</code>&rdquo;"
      person = 'Nurse Greice #1 <span class="subtext">Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a></span>'
      img = "person3.jpg"
      alt = "Person3"
    


  # Services section
  [params.services]
    enable = true
    title = "Serviços"
    description = "Conheça os nossos serviços e formas de atuação."

    [[params.services.item]]
      title = "Enfermeiros"
      description = "Cuidaremos do seu processo de forma personalizada, traçando uma meta realista de acordo com as suas e necessidades e experiência profissional."
      icon = "icon-people"

    [[params.services.item]]
      title = "Universidades &amp; Instituições de Ensino"
      # TODO arrumar o link para Contato
      # TODO Arrumar a cor do link
      # description = 'Oferecemos workshops gratuitos para apresentar essa oportunidade aos alunos e professores. <a href="#" data-nav-section="contact">Entre em contato</a> para saber como.'
      description = 'Oferecemos workshops gratuitos para apresentar essa oportunidade aos alunos e professores. <a href="#contact">Entre em contato</a> para saber como.'
      icon = "icon-graduation"

  # About section
  [params.about]
    enable = true
    title = "Sobre"
    description = "Empresa de recrutamento e consultoria de enfermeiros para os EUA."

    [[params.about.item]]
      name = "Flaviane Morales"
      position = "Fundadora"
      description = "<code class='TODO'>Descrição</code>"
      img = "person1.jpg"
      alt = "Flaviane Morales"
      social = [
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Izabelle Gindri"
      position = "Fundadora"
      description = "<code class='TODO'>Descrição</code>"
      img = "person2.jpg"
      alt = "Izabelle Gindri"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Greice xxx"
      position = "Position"
      description = "<code class='TODO'>Descrição</code>"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]      

    # [[params.about.item]]
    #   name = "Denis C de Azevedo"
    #   position = "CTO"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
    #   img = "person3.jpg"
    #   alt = "Denis C de Azevedo"
    #   social = [
    #     ["icon-twitter", "#"],
    #     ["icon-facebook", "#"],
    #     ["icon-linkedin", "#"],
    #     ["icon-github", "#"]
    #   ]      

  # Counters section
  [params.counters]
    enable = true
    title = "ACP em números"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Pacientes/famílias atendidas"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Enfermeiros contratados"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "A ACP está entre as 5.000 empresas que mais crescem nos EUA"
      icon = "icon-cup"
      # TODO Fazer o número fixo
      from = 5000
      to = 5000
      interval = 50
      speed = 5000


  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Contato"
    description = "Quer fazer parte do nosso time?<br>Tem dúvidas?<br>Entre em contato com a nossa equipe no Brasil."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Florianópolis / SC"],
        ["icon-phone", "+55 (48) 99176-0676 / +55 (48) 99176-3535"],
        ["icon-envelope", "advancedcarebr@gmail.com"],
        ["icon-globe", '<a href="https://www.advancedcarepediatrics.com/" target="_blank">ACP Home care</a>']
      ]

    subject = "Nova mensagem do site!"
    # Form input fields
    name = "Nome"
    email = "Email"
    phone = "Telefone"
    message = "Mensagem"
    button = "Enviar mensagem"

  # Footer section
  [params.footer]
    enable = true
    copyright = "&copy; ACP Recrutamento. Todos os direitos reservados."
    links = [
        ["icon-instagram", "#instagram"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"],
        ["icon-twitter", "#twitter"]
      ]
