# Page settings
baseurl = "https://acpbrasil.github.io/acpbrasil-blog-hugo/"
title = "ACP Brasil"
languageCode = "pt-br"
theme = "elate"

[params]
  
  custom_css = ["css/custom.css"]

  # Meta
  author = ""
  description = ""
  email = "denisazevedo@gmail.com"
  
  # Navigation
  [params.navigation]
    brand = "ACP Brasil"
    home = "Home"
    work = "Processo"
    testimonials = "Testemunhos"
    services = "Serviços"
    contact = "Contato"
    about = "Sobre"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "/blog/"
      name = "Blog"
      weight = 10
  
  # Hero section
  [params.hero]
    # title = "ACP Recrutamento &amp; Consultoria"
    title = "ACP Recrutamento &amp; Consultoria:"
    subtitle = "A enfermagem como passaporte para os EUA."
    description = "Trabalhar como enfermeiro nos EUA com a ACP é a sua oportunidade de encarar novos desafios, expandir seus conhecimentos e alavancar a sua carreira como enfermeiro imerso na cultura americana."
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Quem somos nós?"
    description = "Conheça a ACP Brasil e sua parceira ACP Home Care USA."
    url = "#"
    button = "Saiba mais"
    icon = "icon-people"
    # icon = "icon-question"
    # icon = "icon-info"
    img = "img_10.jpg"

  [[params.intro.item]]
    title = "Requisitos"
    description = "Veja se você se qualifica preenchendo um formulário."
    url = "#"
    button = "Saiba mais"
    icon = "icon-note"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Salários e benefícios"
    description = "Saiba quanto você ganhará trabalhando nos EUA."
    url = "#"
    button = "Saiba mais"
    icon = "icon-wallet"
    img = "img_7.jpg"

  [params.intro.video]
    enable = true
    title = "Assista ao vídeo"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=FSGWhw_RA8Y"


  # Work section
  [params.work]
    enable = true
    title = "Processo"
    description = "Recrutamento de Enfermeiras: A ACP irá junto com você percorrer e transpor todas as etapas necessárias que chamamos de “STEP 1- HOW TO GET CERTIFIED?” para que seu sonho de trabalhar como enfermeiro nos Estados Unidos se torne realidade."
    footertext = '** xxx Algum texto de rodapé se preciso'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Requisitos mínimos"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Teste de proficiência em inglês"
      subtitle = "Qual teste de inglês devo fazer?"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "O que é CGFNS"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Licença"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "NCLEX"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Imigração"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testemunhos"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Em 2007 consegui minha licença pela <em>Board of Nursing Colorado</em>. Contei com uma americana da área da saúde para entender todas as etapas: isso foi fundamental! Passei na 1ª tentativa na prova do Nclex! Não consegui sponsor devido a recessão nos EUA na época. Quando conheci a Greice, fiquei extremamente interessada em participar da ACP Brasil e ajudar colegas com minha experiência a concretizar este sonho!&rdquo;"
      person = 'Flaviane Morales <span class="subtext">Fundadora <a href="http://www.acpbrasil.com/" target="_blank">ACP Brasil</a></span>'
      img = "person1.jpg"
      alt = "Flaviane Morales"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'Nurse Greice #1 <span class="subtext">Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a></span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Nurse Greice #1 <span class="subtext">Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a></span>'
      img = "person3.jpg"
      alt = "Person3"
    


  # Services section
  [params.services]
    enable = true
    title = "Serviços"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Enfermeiras"
      description = "Cuidaremos do seu processo individualmente e caminharemos de mãos dadas por esse processo."
      icon = "icon-people"

    [[params.services.item]]
      title = "Universidades &amp; Instituições de ensino"
      description = "Através de workshops gratuitos levaremos esta oportunidade até vocês. Saiba como."
      icon = "icon-graduation"

  # About section
  [params.about]
    enable = true
    title = "Sobre"
    description = "Empresa de recrutamento e consultoria de enfermeiros para os EUA."

    [[params.about.item]]
      name = "Flaviane Morales"
      position = "Fundadora"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Flaviane Morales"
      social = [
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Izabelle Gindri"
      position = "Fundadora"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Izabelle Gindri"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Greice xxx"
      position = "Position"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]      

    # [[params.about.item]]
    #   name = "Denis C de Azevedo"
    #   position = "CTO"
    #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
    #   img = "person3.jpg"
    #   alt = "Denis C de Azevedo"
    #   social = [
    #     ["icon-twitter", "#"],
    #     ["icon-facebook", "#"],
    #     ["icon-linkedin", "#"],
    #     ["icon-github", "#"]
    #   ]      

  # Counters section
  [params.counters]
    enable = true
    title = "ACP Brasil em números"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Xícaras de café"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Clientes felizes"
      icon = "icon-people"
      from = 0
      to = 2
      interval = 1
      speed = 500

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Contato"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Florianópolis / SC"],
        ["icon-phone", "+55 (48) 99176-0676 / +55 (48) 99176-3535"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="https://www.advancedcarepediatrics.com/" target="_blank">ACP Home care</a>']
      ]

    subject = "Nova mensagem do site!"
    # Form input fields
    name = "Nome"
    email = "Email"
    phone = "Telefone"
    message = "Mensagem"
    button = "Enviar mensagem"

  # Footer section
  [params.footer]
    enable = true
    copyright = "&copy; ACP Brasil. Todos os direitos reservados."
    links = [
        ["icon-instagram", "#instagram"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"],
        ["icon-twitter", "#twitter"]
      ]
