# Page settings
# baseurl = "https://acpbrasil.github.io/acpbrasil-blog-hugo/"
baseurl = "https://www.acpbrasil.com/"
title = "ACP Brasil"
theme = "elate"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-117751277-1"
# Enable comments by entering your Disqus shortname
disqusShortname = "acpbrasil"

# Define the number of posts per page
paginate = 5

# enableInlineShortcodes = true
enableMissingTranslationPlaceholders = false
footnoteReturnLinkContents = "↑" # "↩"
summaryLength = 50  # 70
removePathAccents = true

enableGitInfo = true

# Multilanguage
isMultiLingual = true
defaultContentLanguage = "pt"
# defaultContentLanguage = "pt-br"

# [permalinks]
#   blog = "/blog/:slug/"

[blackfriday]
  fractions = false

[taxonomies]
  category = "categories"
  # category = "categorias"


# Languages (i18n)

# Portuguese ###############
[languages.pt]
  lang = "pt-br"
  languageCode = "pt-br"
  languagePrefix = "pt"
  contentDir = "content/pt"
  languageName = "Português"
  weight = 1
  [[languages.pt.menu.pages]]
    url = "sobre/"
    name = "Quem somos"
    weight = 10
  [[languages.pt.menu.postpend]]
    url = "formulario/"
    name = "Faça parte"
    weight = 10
  [[languages.pt.menu.postpend]]
    url = "blog/"
    name = "Blog"
    weight = 11

  # Params
  [languages.pt.params]
    description = "Empresa de recrutamento e consultoria de enfermeiros para os EUA"
    defaultKeywords = [
      "acp", "blog", "advanced care", "advanced care pediatrics", "advanced care partners", "acp brasil",
      "enfermeiros", "enfermeiros eua", "enfermeiros estados unidos", "recrutamento",
    ]
    # Navigation
    [languages.pt.params.navigation]
      brand = "ACP Brasil"
      home = "Home"
      work = "Por que a ACP?"
      services = "Serviços"
      # testimonials = "Testemunhos"
      about = "Sobre"
      contact = "Contato"


# English ###############
[languages.en]
  lang = "en"
  languageCode = "en-us"
  languagePrefix = "en"
  contentDir = "content/en"
  languageName = "English"
  weight = 2
  [[languages.en.menu.pages]]
    url = "about/"
    name = "About us"
    weight = 10
  [[languages.en.menu.postpend]]
    url = "form/"
    name = "Join us"
    weight = 10
  [[languages.en.menu.postpend]]
    url = "blog/"
    name = "Blog"
    weight = 11
  
  # Params
  [languages.en.params]
    # TODO i18n: US ou USA?
    description = "Nursing Recruitment & Consulting Company for the USA"
    defaultKeywords = [
      "acp", "blog", "advanced care", "advanced care pediatrics", "advanced care partners", "acp brasil",
      "nursing eua", "nurses usa", "recruiting", "immigration", "nurse jobs"
    ]
    # Navigation
    [languages.en.params.navigation]
      brand = "ACP Brasil"
      home = "Home"
      work = "Why ACP?"
      services = "Services"
      about = "About"
      contact = "Contact"


# Spanish ###############
[languages.es]
  lang = "es"
  languageCode = "es"
  languagePrefix = "es"
  contentDir = "content/es"
  languageName = "Español"
  weight = 3
  [[languages.es.menu.pages]]
    url = "sobre/"
    name = "Quiénes somos"
    weight = 10
  [[languages.es.menu.postpend]]
    url = "formulario/"
    name = "Únase a nosotros"
    # name = "Únete"
    weight = 10
  [[languages.es.menu.postpend]]
    url = "blog/"
    name = "Blog"
    weight = 11
  
  # Params
  [languages.es.params]
    description = "Empresa de contratación y consultoria de enfermeros para los Estados Unidos"
    defaultKeywords = [
      "acp", "blog", "advanced care", "advanced care pediatrics", "advanced care partners", "acp brasil",
      "enfermeros", "enfermeros eua", "enfermeros usa", "contratación", "migración", "empleo"
    ]
    # Navigation
    [languages.es.params.navigation]
      brand = "ACP Brasil"
      home = "Inicio"
      work = "¿Por qué ACP?"
      services = "Servicios"
      about = "Acerca de"
      contact = "Contacto"


[params]
  socialSharing = true
  date_format = "2 January, 2006"  # Format dates with Go's time formatting
  
  custom_css = ["css/custom.css"] # Custom CSS files for Home page

  # Meta
  author = "ACP Brasil, Denis C de Azevedo <denis.azevedo@gmail.com>"
  email = "contato@acpediatrics.com"

  # Enable Google Tag Manager by entering your id
  googleTagManager = "GTM-WDLFDV2"
  # Enable Facebook Pixel Code by entering your id
  facebookPixel = "250954482129336"
  # Enable LinkedIn Insight by entering your partner id
  linkedinInsight = "430226"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  # FIXME i18n: Precisa liberar urls /en e /es ???
  googleMapsApiKey = "AIzaSyAjfJiRAe8ct6XKSaHSEXp49sXZBLdmy0Q"

  # URL para a Landing Page para download do ebook (configurado no RD Station)
  ebookLandingPageUrl = "https://conteudos.acpbrasil.com/ebook-enfermeiro-nos-eua?utm_source=display&utm_medium=banner_blog_posts"

  defaultKeywords = [ "acp", "blog", "advanced care", "advanced care pediatrics", "acp brasil" ]

  # Forms configuration
  emailsSubjectPrefix = "[ACP]"

  # Hero section
  [params.hero]
    videoUrl = "https://www.advancedcarepartners.com/wp-content/uploads/2017/03/homepage-header.mp4"
    videoImage = "bg/homepage-header-still.jpg"
 
  # Intro section
  [params.intro]
    [params.intro.video]
      enable = true
      icon = "icon-play2"
      # url = "https://www.youtube.com/watch?v=QWJAwVH1ULY"
      # url = "https://vimeo.com/267397018/0b8ed33c67"
      url = "https://vimeo.com/267397018"
      vimeo_id = "267397018"

  # Work section
  [params.work]
    enable = true
    dataContent = "porqueacp" # Arquivo dentro de data/ com o conteúdo dessa seção

  # Testimonials section
  [params.testimonials]
    enable = true

  # Services section
  [params.services]
    enable = true

  # About section
  [params.about]
    enable = true
    # [[params.about.item]]
    #   name = "Greice"
    #   position = "Fundadora"
    #   description = "<code class=''>Descrição</code>"
    #   img = "person1.jpg"
    #   alt = "Greice"
    #   # social = [
    #   #   ["icon-facebook", "#"],
    #   #   ["icon-linkedin", "#"]
    #   #   ["icon-twitter", "#"],
    #   # ]      
    # [[params.about.item]]
    #   name = "Flaviane"
    #   position = "Consultora"
    #   description = "<code class=''>Descrição</code>"
    #   img = "person2.jpg"
    #   alt = "Flaviane"
    #   # social = [
    #   #   ["icon-facebook", "#"],
    #   #   ["icon-linkedin", "#"]
    #   # ]
    # [[params.about.item]]
    #   name = "Izabelle"
    #   position = "Consultora"
    #   description = "<code class=''>Descrição</code>"
    #   img = "person3.jpg"
    #   alt = "Person3"
    #   # social = [
    #   #   ["icon-facebook", "#"],
    #   #   ["icon-linkedin", "#"]
    #   #   ["icon-twitter", "#"],
    #   # ]
    

  # Counters section
  [params.counters]
    enable = true
    background = "full_image_1.jpg"

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = false
    subject = "Nova mensagem do site!"  # Home page contact form
    emailTo = "contato@acpediatrics.com"
    emailCc = [
      "fmorales@acpbrasil.com",
      "igindri@acpbrasil.com"
    ]
    details = [  # Available icons: https://simplelineicons.github.io
      ["icon-home", "Florianópolis / SC"],
      ["icon-phone", "+55 (48) 99176-0676<br>+55 (48) 99176-3535"],
      ["icon-envelope", "<a href='mailto:contato@acpediatrics.com?subject=Contato'>contato@acpediatrics.com</a>"],
      ["icon-globe", '<a href="https://www.advancedcarepartners.com/" target="_blank">ACP Home care</a><br><a href="https://www.acpbrasil.com/" target="_blank">ACP Brasil</a>']
    ]


  # Footer section
  [params.footer]
    enable = true
    privacyPolicy = true
    links = [
        ["icon-instagram", "https://www.instagram.com/acpbrasil_enfermeiroseua/"],
        # TODO Mudar o link do Facebook pra acpbrasil
        ["icon-facebook", "https://www.facebook.com/enfermeiroseua"],
        ["icon-twitter", "https://twitter.com/acpartnersbr"],
        ["icon-linkedin", "https://www.linkedin.com/company/acp-brasil-enfermeiros-eua"],
        ["icon-youtube", "https://www.youtube.com/c/ACPBrasil"],
      ]

  # Enable and disable widgets for the right sidebar
  [params.widgets]
    search = true
    categories = true
    tags = false
